name: cane_aid_app
description: "A new Flutter project integrating Bluetooth, voice, and localization features."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI and design
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

  # Bluetooth Low Energy (Updated to non-deprecated version)
  flutter_blue_plus: ^1.32.12

  # Text-to-Speech
  flutter_tts: ^4.2.3

  # Haptic feedback / vibration
  vibration: ^3.1.3

  # Localization and i18n
  flutter_localizations:
    sdk: flutter
  intl: any
  intl_utils: ^2.8.8

  # HTTP requests (for API calls like RGB → color name)
  http: ^1.4.0

  # Location services for GPS
  geolocator: ^13.0.1
  
  # Permission handling
  permission_handler: ^11.3.1


  # State management
  provider: ^6.1.2

  # Local storage for offline features
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # JSON serialization
  json_annotation: ^4.9.0

  # Logging
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true

  # Assets for images, icons, and other resources
  assets:
    - assets/images/
    - assets/icons/

  # Generate localization files
  generate: true
